apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-html
  namespace: nginx-html
spec:
  selector:
    matchLabels:
      app: nginx-html
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-html
    spec:
      containers:
      - name: nginx-html
        image: sercanyz/nginx-html:latest
        ports:
        - containerPort: 5000

---
  
apiVersion: v1
kind: Service
metadata:
  name: nginx-html
  namespace: nginx-html
spec:
  type: LoadBalancer
  selector:
    app: nginx-html
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-html
  namespace: nginx-html
spec:
  ingressClassName: traefik
  rules:
  - host: "nginx-html.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-html
            port:
              number: 5000